name: Musings of a Wayward Sinner
favicon: null
layout_spectrum: 0.9753930373117328
typography_spectrum: 0.3681585353333503
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.9912869341205806
  lightness: 0.7349395947530866
  saturation: 0.23326015775091946
  rhythmicContrast: 0.6248744437471032
purpose: []
